### ISSUE TITLE
Can we Install MRTrix and TORTOISE?

### ISSUE THREAD

**Issue by arash-n** [TIGRLab/quarantine#8]
Hi Guys,

Here are two powerful diffusion imaging toolboxes.

TORTOISE is for preprocessing. I haven't used it myself but is really gaining popularity. 

https://science.nichd.nih.gov/confluence/display/nihpd/TORTOISE

The other one is MRTrix that I have just tried on my home desktop and it seem very very promising. Installation looks simple:

https://github.com/MRtrix3/mrtrix3/wiki/Installing-on-Linux

First we should install the dependencies that probably already have, clone it from github, and build it:

sudo apt-get install git g++ python libgsl0-dev zlib1g-dev libqt4-opengl-dev libgl1-mesa-dev
git clone https://github.com/MRtrix3/mrtrix3.git
cd mrtrix3
./configure
./build

All of the command lines will work with this. But some of its GUIs need high versions of QT. What I don't know is our QT version or if we even have it. 

Cheers,
Arash

**Comment by pipitone** [comment]
This issue was moved to TIGRLab/admin#219
